development: &default
  adapter: postgresql
  encoding: utf8
  database: leaderboard_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: leaderboard_test

production:
  <<: *default
  database: leaderboard_development
